using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MoveMent3rdPerson : MonoBehaviour

    //10.04.22 https://www.youtube.com/watch?v=7mPxoViG-qg&ab_channel=bpcrews
    //https://www.youtube.com/watch?v=_BRiuS8OxWA&ab_channel=bpcrews 

{
    public CharacterController controller;
    public Transform cam;
    public Transform groundCheck;
    public LayerMask groundMask;
    public float speed = 6f;
    public float jump= 3f;
    public float turnSmoothTime = 0.1f;    
    public float gravity = -9.81f;
    public float groundDistance = 0.2f;

    private float turnSmoothVelocity;
    private Vector3 velocity;
    private bool isGrounded;

    private Rigidbody rigid;
    
    void Start()
    {
        rigid = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {       
        
        isGrounded = Physics.CheckSphere(groundCheck.position, groundDistance, groundMask);
        
        if (isGrounded && velocity.y < 0)
        {
            velocity.y = -2f;
        }

        float moveLR = Input.GetAxisRaw("Horizontal")   ;
        float moveFB = Input.GetAxisRaw("Vertical");
        Vector3 direction = new Vector3(moveLR, 0f, moveFB).normalized;

        if (direction.magnitude > 0.1f)
        {
            float targetAngle = Mathf.Atan2(direction.x, direction.z) * Mathf.Rad2Deg + cam.eulerAngles.y;
            float angle = Mathf.SmoothDampAngle(transform.eulerAngles.y, targetAngle, ref turnSmoothVelocity, turnSmoothTime);
            transform.rotation = Quaternion.Euler(0f, angle, 0f);

            Vector3 moveDir = Quaternion.Euler(0f, targetAngle, 0f) * Vector3.forward;
            controller.Move(moveDir * speed * Time.deltaTime);                    
        }

        //Jump
        if(Input.GetButtonDown("Jump") && isGrounded)
        {
            velocity.y = Mathf.Sqrt(jump * -2.0f * gravity);
        }

        velocity.y += gravity * Time.deltaTime;
        controller.Move(velocity * Time.deltaTime);        
    }
}
